dataBaseURL: jdbc:postgresql://localhost:5431/koi
dataBaseUsername: postgres
dataBasePassword: Ga.4567.
logbackURL: http://localhost:8000/native/native/main/LogConfiguration/AuthServerLogback.xml
eurakaUsername: grkem
eurakaPassword: 1234
eurakaIP: localhost:8001/eureka/
resetPasswordTokenExpriationMinute: 2
activeAccountTokenExpriationMinute: 60
resetPasswordTokenLength: 8
activeAccountTokenLength: 8
log4j:
    appender:
        hb: org.apache.log4j.ConsoleAppender
        hb.Threshold: TRACE
        hb.layout: org.apache.log4j.PatternLayout
        hb.layout.ConversionPattern: HibernateLog --> %d{HH:mm:ss} %-5p %c - %m%n
    logger:
        org:
            hibernate: INFO, hb
            hibernate.SQL: DEBUG
            hibernate.cache: info
            hibernate.hql: debug
            hibernate.hql.ast.AST: info
            hibernate.jdbc: debug
            hibernate.tool.hbm2ddl: warn
            hibernate.type: TRACE

server:
  port: 8004
  error:
    include-message: always
    include-binding-errors: always
spring:
  rabbitmq:
    user: guest
    password: guest
    host: localhost
    port: 5672
  application:
    name: AUTH-SERVER
  datasource:
    username: ${dataBaseUsername}
    url: ${dataBaseURL}
    password: ${dataBasePassword}
  jpa:
    show-sql: true
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
      database: postgresql
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
sample:
  rabbitmq:
    exchange: default
    emailWithHtmlQueue: emailWithHtmlQueue
    emailWithHtmlQueueRoute: emailWithHtmlQueueRoute
    emailQueue: emailQueue
    emailQueueRoute: emailQueueRoute
    multipleEmailWithHtmlQueue: multipleEmailWithHtmlQueue
    multipleEmailWithHtmlQueueRoute: multipleEmailWithHtmlQueueRoute
    multipleEmailQueue: multipleEmailQueue
    multipleEmailQueueRoute: multipleEmailQueueRoute
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eurakaUsername}:${eurakaPassword}@${eurakaIP}
    healthcheck:
      enabled: true
logging:
  config: ${logbackURL}
