dataBaseURL: jdbc:postgresql://localhost:5431/koi
dataBaseUsername: postgres
dataBasePassword: Ga.4567.
logbackURL: http://localhost:8000/native/native/main/LogConfiguration/CommentServiceLogback.xml
eurakaUsername: grkem
eurakaPassword: 1234
eurakaIP: localhost:8001/eureka/

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

sample.rabbitmq.exchange=default
sample.rabbitmq.queue=firstStepQueue
sample.rabbitmq.routingKey=firstRoute

server:
  port: 8602
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: COMMENT-SERVICE
  datasource:
    username: ${dataBaseUsername}
    url: ${dataBaseURL}
    password: ${dataBasePassword}
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
      database: postgresql
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
sample:
  rabbitmq:
    exchange: default
    updateUserDetailQueue: updateUserDetailQueue
    routingKey: updateUserDetailRoute
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eurakaUsername}:${eurakaPassword}@${eurakaIP}
    healthcheck:
      enabled: true
logging:
  config: ${logbackURL} 
