logbackURL: http://localhost:8000/native/native/main/LogConfiguration/EmailServiceLogback.xml
eurakaUsername: grkem
eurakaPassword: 1234
eurakaIP: localhost:8001/eureka/

server:
  port: 8010
spring:
  application:
    name: EMAIL-SERVICE
  mail:
    username: test.koi.project@gmail.com
    password:  "dgrk fpec iwsz qzld"
    properties:
      mail:
        smtp:
          host: smtp.gmail.com
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          port: 465
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eurakaUsername}:${eurakaPassword}@${eurakaIP}
    healthcheck:
      enabled: true
logging:
  config: ${logbackURL}
