logbackURL: http://localhost:8000/native/native/main/LogConfiguration/EmailServiceLogback.xml
eurakaUsername: grkem
eurakaPassword: 1234
eurakaIP: localhost:8001/eureka/

server:
  port: 8010
spring:
  application:
    name: EMAIL-SERVICE
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: test_koi_project@outlook.com
    password: Gg123456
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eurakaUsername}:${eurakaPassword}@${eurakaIP}
    healthcheck:
      enabled: true
logging:
  config: ${logbackURL}
