dataBaseURL: jdbc:postgresql://localhost:5431/koi
dataBaseUsername: postgres
dataBasePassword: Ga.4567.
logbackURL: http://localhost:8000/native/native/main/LogConfiguration/EventServiceLogback.xml
eurakaUsername: grkem
eurakaPassword: 1234
eurakaIP: localhost:8001/eureka/

event:
  lastUpdateDateline: 5
  eventSaveMinStar: 2.5
  
server:
  port: 8601
  error:
    include-message: always
    include-binding-errors: always
spring:
  rabbitmq:
    user: guest
    password: guest
    host: localhost
    port: 5672
  application:
    name: EVENT-SERVICE
  datasource:
    username: ${dataBaseUsername}
    url: ${dataBaseURL}
    password: ${dataBasePassword}
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
      database: postgresql
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
sample:
  rabbitmq:
    exchange: default
    updateUserRemainingQueue: updateUserRemainingQueue
    updateUserRemainingRoute: updateUserRemainingRoute
    emailWithHtmlQueue: emailWithHtmlQueue
    emailWithHtmlQueueRoute: emailWithHtmlQueueRoute
    emailQueue: emailQueue
    emailQueueRoute: emailQueueRoute
    multipleEmailWithHtmlQueue: multipleEmailWithHtmlQueue
    multipleEmailWithHtmlQueueRoute: multipleEmailWithHtmlQueueRoute
    multipleEmailQueue: multipleEmailQueue
    multipleEmailQueueRoute: multipleEmailQueueRoute
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eurakaUsername}:${eurakaPassword}@${eurakaIP}
    healthcheck:
      enabled: true
logging:
  config: ${logbackURL}
