logbackURL: http://localhost:8000/native/native/main/LogConfiguration/GatewayServerLogback.xml
eurakaUsername: grkem
eurakaPassword: 1234
eurakaIP: localhost:8001/eureka/


resilience4j:
  circuitbreaker:
    configs:
      defaultCircuitbreaker:
        slidingWindowType: COUNT_BASED #Kayıt altına alınan data kıstası. Saniye olarakta belirlenebilmektedir.
        slidingWindowSize: 10 #Son x datanın dikkate alınmasını sağlar.
        minimumNumberOfCalls: 5 #Asgari kayıt sayısını belirler. Bu kayıt sayısından sonra algoritmalar çalışacaktır.
        permittedNumberOfCallsInHalfOpenState: 2 #Sigora yarı açıkken yapılacak max kayıt sayısı.
        automaticTransitionFromOpenToHalfOpenEnabled: true #Sigortanın açık konumdan yarı-açık konuma gelmesini üsrecinin atomatize edilmesi sağlar.
        failureRateThreshold: 50 #% cinsinden ne kadar bir fail oranı olursa sigorta açık konuma gelecek bilgisi girilir.
        waitDurationInOpenState: 60s #Açık olan devre saniye sonra yarı açık hal gelecektir.
        slowCallDurationThreshold: 30s #Saniye üzerinde dönen request'leri yavaş olarak kabul edecektir.
        slowCallRateThreshold: 90 #Yavaş request sayısı %x'i aşarsa sigorta yarı-açık konuma gelecektir.
        registerHealthIndicator: true
    instances:
      fallbackAuth:
        baseConfig: defaultCircuitbreaker
      fallbackUser:
        baseConfig: defaultCircuitbreaker
      fallbackEvent:
        baseConfig: defaultCircuitbreaker
      fallbackComment:
        baseConfig: defaultCircuitbreaker
      fallbackParticipant:
        baseConfig: defaultCircuitbreaker
  timelimiter:
    configs:
      defaultTimelimiter:
        timeoutDuration: 20s
    instances:
      fallbackAuth:
        baseConfig: defaultTimelimiter
      fallbackUser:
        baseConfig: defaultTimelimiter
      fallbackEvent:
        baseConfig: defaultTimelimiter
      fallbackComment:
        baseConfig: defaultTimelimiter
      fallbackParticipant:
        baseConfig: defaultTimelimiter

server:
  port: 8002
spring:
  main:
    web-application-type: reactive
  application:
    name: GATEWAY-SERVER
  cloud:
    gateway:
      routes:
        - id: authServer
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: fallbackAuth
                fallbackUri: forward:/fallbackAuthServer
             - name: RequestRateLimiter
               args:
                 redis-rate-limtter.replenishRate: 20
                 redis-rate-limtter.burstCapacity: 40
                 redis-rate-limtter.requestedTokens: 1
        - id: userDetailService
          uri: lb://USER-DETAIL
          predicates:
            - Path=/userDetail/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: fallbackUser
                fallbackUri: forward:/fallbackUserDetailService
        - id: eventService
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/event/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: fallbackEvent
                fallbackUri: forward:/fallbackEventService
        - id: commentService
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comment/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: fallbackComment
                fallbackUri: forward:/fallbackCommentService
        - id: participantService
          uri: lb://PARTICIPANT-SERVICE
          predicates:
            - Path=/participant/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: fallbackParticipant
                fallbackUri: forward:/fallbackParticipantService
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eurakaUsername}:${eurakaPassword}@${eurakaIP}
    healthcheck:
      enabled: true
      management:
management:
  endpoints:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    web:
      exposure:
        include: "*"
logging:
  config: ${logbackURL}
  level:
    org.springframework.cloud.gateway: DEBUG
    io.github.resilience4j: DEBUG
