logbackURL: http://localhost:8000/native/native/main/LogConfiguration/GatewayServerLogback.xml
eurakaUsername: grkem
eurakaPassword: 1234
eurakaIP: localhost:8001/eureka/


server:
  port: 8002
spring:
  main:
    web-application-type: reactive
  application:
    name: GATEWAY-SERVER
  cloud:
    gateway:
      routes:
        - id: authServer
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: fallbackAuth
                fallbackUri: forward:/fallbackAuthServer
        - id: userDetailService
          uri: lb://USER-DETAIL
          predicates:
            - Path=/userDetail/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: fallbackUser
                fallbackUri: forward:/fallbackUserDetailService
        - id: eventService
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/event/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: fallbackEvent
                fallbackUri: forward:/fallbackEventService
        - id: commentService
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comment/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: fallbackComment
                fallbackUri: forward:/fallbackCommentService
        - id: participantService
          uri: lb://PARTICIPANT-SERVICE
          predicates:
            - Path=/participant/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: fallbackParticipant
                fallbackUri: forward:/fallbackParticipantService
resilience4j:
  circuitbreaker:
    configs:
      defaultCircuitbreaker:
        failureRateThreshold: 51
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
    instances:
      fallbackAuth:
        baseConfig: defaultCircuitbreaker
      fallbackUser:
        baseConfig: defaultCircuitbreaker
      fallbackEvent:
        baseConfig: defaultCircuitbreaker
      fallbackComment:
        baseConfig: defaultCircuitbreaker
      fallbackParticipant:
        baseConfig: defaultCircuitbreaker
  timelimiter:
    configs:
      defaultTimelimiter:
        timeoutDuration: 20s
    instances:
      fallbackAuth:
        baseConfig: defaultTimelimiter
      fallbackUser:
        baseConfig: defaultTimelimiter
      fallbackEvent:
        baseConfig: defaultTimelimiter
      fallbackComment:
        baseConfig: defaultTimelimiter
      fallbackParticipant:
        baseConfig: defaultTimelimiter
  ratelimiter:
    configs:
      defaultRatelimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 5s
        registerHealthIndicator: true
        subscribeForEvents: true
    instances:
      fallbackAuth:
        baseConfig: defaultRatelimiter
      fallbackUser:
        baseConfig: defaultRatelimiter
      fallbackEvent:
        baseConfig: defaultRatelimiter
      fallbackComment:
        baseConfig: defaultRatelimiter
      fallbackParticipant:
        baseConfig: defaultRatelimiter
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eurakaUsername}:${eurakaPassword}@${eurakaIP}
    healthcheck:
      enabled: true
      management:
management:
  endpoints:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    web:
      exposure:
        include: "*"
logging:
  config: ${logbackURL}
